
  - name: Get Nexus facts
    nxos_facts:

  - name: "Create VLAN and SVI"
    nxos_config:
      src: "NX_VLAN.j2"
      match: none
      save_when: modified
    when: (vlan.id |string) not in ansible_net_vlan_list

